project_id = "vwnkziovsjhrsqokmfzi"

[functions.bodacc-api]
verify_jwt = false

[functions.extrapolate-analysis]
verify_jwt = false

[functions.pappers-api]
verify_jwt = false

[functions.predictor-analysis]
verify_jwt = false

[functions.rubypayeur-api]
verify_jwt = false

[functions.sirene-search]
verify_jwt = false

[functions.web-scraper]
verify_jwt = false

[functions.outscrapper-search]
verify_jwt = false

[functions.apollo-search]
verify_jwt = false

[functions.infogreffe-api]
verify_jwt = false

[functions.insee-api]
verify_jwt = false

[functions.enrich-company-data]
verify_jwt = false