// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwnkziovsjhrsqokmfzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3bmt6aW92c2pocnNxb2ttZnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzI2MDUsImV4cCI6MjA3Mzg0ODYwNX0.xc4C8hX6tWFw0LeA-czR0shzQT9ZVMZm4GEczIYeJK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});